### ISSUE TITLE
Incomptatible versions of GCC and CUDA in yml file

### ISSUE THREAD

**Issue by DylanWangWQF** [IntelLabs/PyTorchALFI#21]
Hi @SyedShaQutub 
In the `yml` file, you specify the version of GCC (e.g., `gcc_linux-64`) as 11.2.0 and CUDA as 11.3, however, it outputs the following mismatch error:
`The current installed version of /home/qifan/anaconda3/envs/pytorchALFI/bin/x86_64-conda-linux-gnu-c++ (11.2.0) is greater than the maximum required version by CUDA 11.3 (10.0.0). Please make sure to use an adequate version of /home/qifan/anaconda3/envs/pytorchALFI/bin/x86_64-conda-linux-gnu-c++ (>=5.0.0, <=10.0.0).`

The cause of this is`cudatoolkit`? I guess some versions in `condaenv.yml` should be updated?

Some of my testbed:
```
conda 24.1.2

//  cudatookit 11.3 is installed to match the `yml` file
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0
```

**Comment by SyedShaQutub** [comment]
Hi @DylanWangWQF, 
Thanks for trying out our repo. The yml file contains some issues, especially the unnecessary packages. Regarding the GCC version mismatch, you could update the code to the latest version or install the combined gcc to match it with Cuda. 
There is also another solution; please refer to this page - https://stackoverflow.com/questions/6622454/cuda-incompatible-with-my-gcc-version.

Let me know if it works

**Comment by DylanWangWQF** [comment]
@SyedShaQutub 
Thanks for your suggestion! I will try later since my GPU machine doesn't work now. 

>  you could update the code to the latest version

It's the latest. I just cloned the repo several days ago. So I think anyone sets up according to `yml` file recently, he will get the same error.

>  install the combined gcc to match it with Cuda.

I will try to `ln -s` GCC link in conda env and see if it works.
