### ISSUE TITLE
sdc_eval folder empty after running obj_dect_analysis.py

### ISSUE THREAD

**Issue by syedtihaamahmad** [IntelLabs/PyTorchALFI#4]
When I try to run obj_dect_analysis.py the terminal output is the following :

_**epoch 0 ...
images without annotations set()**_

and sdc_eval folder is empty.

**Comment by SyedShaQutub** [comment]
@syedtihaamahmad I remember this issue and there could be multiple reasons. We had fixed all of these issues before the release. 
Just to cross-verify again, do you see the same error if you run your fault injection experiment set using batch_size=1?
If possible, could you please paste the error trace, especially the failing inner function of the main function **obj_det_analysis_func** located at ./pytorchalfi/alficore/evaluation/sdc_plots/obj_det_analysis.py. We could point you to the exact issue.
