### ISSUE TITLE
AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute 'next'

### ISSUE THREAD

**Issue by sajidahmed12** [IntelLabs/PyTorchALFI#5]
Issue:  While Running:  !python demo_obj_detection.py
![image](https://user-images.githubusercontent.com/28151933/207897530-60fcab88-1212-4eac-8d36-eb93fe504864.png)

In dir alfiecore/dataloader/abs_loader.py, the function `datagen_itr` the following modification needs to be made. 

The solution 
datagen_itr(self at abs_loader.py
` datagen_itr(self):
        if self.data_incoming == True:
            self.data = next(self.datagen_iter) 
`

Solution link: https://stackoverflow.com/questions/74289077/attributeerror-multiprocessingdataloaderiter-object-has-no-attribute-next

**Comment by SyedShaQutub** [comment]
Hi @sajidahmed12 
Happy Holidays and sorry for the late response. Could you please point us to the scenario file you used to run this demo experiment along with any modifications you did on this file as per your need? 
This problem suggests that there is possibly a breakdown of the data loader. This is not the case! checked as I checked on my side for any possible issues. I'm certain that the data loader is working fine, maybe I'm missing more details here. Please let me know if there is any.

The solution you suggested makes the entire class a generator and this is not the intention as we derive many other methods and variables from this class.

What dataset did you use (CoCo2017/Kitti/..etc...)?
How is your dataset format defined?
Also, I would suggest to the go through the data loader section in our wiki page (https://github.com/IntelLabs/pytorchalfi/tree/f51f5086f73e227af984ce0ad74e2b8e65363255#dataloaders)

**Comment by SyedShaQutub** [comment]
Fixed this issue with a generic solution as this varies between different python versions
